### ISSUE TITLE
Support for selecting specific columns

### ISSUE THREAD

**Issue by metasoarous** [onyx-platform/onyx-sql#10]
Instead of `SELECT * FROM ...` would be nice to select only a handful of columns via a `:sql/columns` attribute.

**Comment by mushketyk** [comment]
@MichaelDrogalis @lbradstreet What do you think about this?
Don't you mind if I give it a try?

**Comment by MichaelDrogalis** [comment]
Sure, go for it!

**Comment by sventech** [comment]
Is this issue fixed with this pull request?
https://github.com/onyx-platform/onyx-sql/pull/13

**Comment by MichaelDrogalis** [comment]
Yes, thanks!
