### ISSUE TITLE
upsert don't insert row automatically.

### ISSUE THREAD

**Issue by ghost** [onyx-platform/onyx-sql#17]
i'm trying to refresh website data to oracle database in real time by per 5 seconds.
this is the code.
https://github.com/larluo/9now/blob/master/workspace/onyx-umeng/src/onyx_umeng/core.clj

but the record don't insert automatically, it'll update data only.
i also explore the plugin code,  it seems you don't check the key existence.
only update it directly.

``` clojure
(defrecord SqlUpsertRows [pool table]
  p-ext/Pipeline
  (read-batch 
    [_ event]
    (function/read-batch event))

  (write-batch
    [_ {:keys [onyx.core/results onyx.core/task-map sql/pool]}]
    (doseq [msg (mapcat :leaves (:tree results))]
      (jdbc/with-db-transaction
        [conn pool]
        (doseq [row (:rows (:message msg))]
          (jdbc/update! conn (:sql/table task-map) row (sql-dsl/where (:where (:message msg)))))))
    {:sql/written? true})

  (seal-resource 
    [_ event]
    {}))
```

**Comment by gardnervickers** [comment]
Good catch, we should consider changing the name to SqlUpdateRows instead of claiming the ability to do an Upsert.

**Comment by larluo** [comment]
i think the upset can be completed by (delete/insert) with configure parameter.
 the upsert function is very useful sometimes.

**Comment by MichaelDrogalis** [comment]
Done!
