### ISSUE TITLE
is onyx-seq still a recommendation in12.x? 

### ISSUE THREAD

**Issue by joefromct** [onyx-platform/onyx-sql#34]
From the readme: 

> In the mean time, if you don't have an integer key column it's recommended you use the onyx-seq plugin and read rows in using a single SELECT query

Is this still the recommendation with [onyx-seq](https://github.com/onyx-platform/onyx-seq) being v 0.9.x and archived ? 

I've just been using a function to dump db results onto an async channel, than (patiently) starting my workflow input from there. 

Thanks,

**Comment by lbradstreet** [comment]
Hi, yes, it's still recommended but it's been moved to onyx core. I've updated the link to now link to: https://github.com/onyx-platform/onyx/blob/0.12.x/src/onyx/plugin/seq.clj. We'll fix up the docs soon.

Thanks for the note. I hadn't realised that the link was bad.
